### ISSUE TITLE
Need GNSS RINEX observation factor

### ISSUE THREAD

**Issue by impce-lg** [shaolinbit/minisam_lib#2]
Hey Doc.Lv,
U may know that many scholars research GNSS topics with the RINEX data，including Pesudorange and PhaseCarrier observations, the Optimization methods have always been KF or its variants.
If some RINEX observation factors are added, i think many GNSSers will try them in their work.
Will u please consider about this when you have time? 
The following references may be helpful:
#1 https://github.com/wvu-navLab/PPP-BayesTree
#2 https://github.com/wvu-navLab/RobustGNSS
Many thanks in advance

**Comment by shaolinbit** [comment]
Now pppbayestree is added.
However, Dogleg is not supported yet. It will come soon.
Now, only Gaussian Newton method is supported.

**Comment by impce-lg** [comment]
3q，nice of u
